[fsaverage]
git-tree-sha1 = "4fac17b48a20ee5fc8edbdb179d4e5ad96fa4d51"

[[fsaverage.download]]
url = "https://osf.io/download/s2tay"
sha256 = "a871511c2a9b1ac214e9050943eac2e95b546ef24de307f193e27c5e4ac062a0"                                                                                                              